FROM nginx:alpine

#!/bin/sh

COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

EXPOSE 3000

ENTRYPOINT ["nginx", "-g", "daemon off;"]